change pipeline

diff --git a/.github/workflows/reviewdog.yaml b/.github/workflows/reviewdog.yaml
--- a/.github/workflows/reviewdog.yaml
+++ b/.github/workflows/reviewdog.yaml
@@ -11,6 +11,10 @@ on:
 env:
   TERRAFORM_VERSION: "1.0.6"
 
+defaults:
+  run:
+    shell: bash
+
 jobs:
 
   tflint:
@@ -46,16 +50,16 @@ jobs:
           filter_mode: "nofilter" # Optional. Check all files, not just the diff
           level: info
           flags: "--module" # Optional. Add custom tflint flags
-  tfsec:
-    name: tfsec report
-    runs-on: ubuntu-latest
+  # tfsec:
+  #   name: tfsec report
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Clone repo
-        uses: actions/checkout@master
+  #   steps:
+  #     - name: Clone repo
+  #       uses: actions/checkout@master
 
-      - name: tfsec
-        uses: reviewdog/action-tfsec@master 
+  #     - name: tfsec
+  #       uses: reviewdog/action-tfsec@master 
   test-check:
     name: tfsec (github-check)
     runs-on: ubuntu-latest
@@ -66,12 +70,6 @@ jobs:
       - uses: ./
         continue-on-error: true
         id: test
-        with:
-          github_token: ${{ secrets.github_token }}
-          reporter: github-check
-          level: info
-          working_directory: testdata
-
       # The check is expected to fail on the test data
       - name: Check return codes
         if: success() || failure ()
@@ -90,75 +88,75 @@ jobs:
             echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
             exit 1
           fi
-  test-pr-check:
-    if: github.event_name == 'pull_request'
-    name: tfsec (github-pr-check)
-    runs-on: ubuntu-latest
+  # test-pr-check:
+  #   if: github.event_name == 'pull_request'
+  #   name: tfsec (github-pr-check)
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v3
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - uses: ./
-        continue-on-error: true
-        id: test
-        with:
-          github_token: ${{ secrets.github_token }}
-          reporter: github-pr-check
-          level: info
-          working_directory: testdata
+  #     - uses: ./
+  #       continue-on-error: true
+  #       id: test
+  #       with:
+  #         github_token: ${{ secrets.github_token }}
+  #         reporter: github-pr-check
+  #         level: info
+  #         working_directory: testdata
 
-      # The check is expected to fail on the test data
-      - name: Check return codes
-        if: success() || failure ()
-        run: |
-          tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
-          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
-          if [[ "$tfsec_return" -eq 1 ]]; then
-            echo "tfsec correctly returned failure ${tfsec_return}"
-          else
-            echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
-            exit 1
-          fi
-          if [[ "$reviewdog_return" -eq 0 ]]; then
-            echo "reviewdog correctly returned success: ${reviewdog_return}"
-          else
-            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
-            exit 1
-          fi
-  test-pr-review:
-    if: github.event_name == 'pull_request'
-    name: tfsec (github-pr-review)
-    runs-on: ubuntu-latest
+  #     # The check is expected to fail on the test data
+  #     - name: Check return codes
+  #       if: success() || failure ()
+  #       run: |
+  #         tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
+  #         reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
+  #         if [[ "$tfsec_return" -eq 1 ]]; then
+  #           echo "tfsec correctly returned failure ${tfsec_return}"
+  #         else
+  #           echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
+  #           exit 1
+  #         fi
+  #         if [[ "$reviewdog_return" -eq 0 ]]; then
+  #           echo "reviewdog correctly returned success: ${reviewdog_return}"
+  #         else
+  #           echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
+  #           exit 1
+  #         fi
+  # test-pr-review:
+  #   if: github.event_name == 'pull_request'
+  #   name: tfsec (github-pr-review)
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v3
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - uses: ./
-        continue-on-error: true
-        id: test
-        with:
-          github_token: ${{ secrets.github_token }}
-          reporter: github-pr-review
-          level: info
-          working_directory: testdata
+  #     - uses: ./
+  #       continue-on-error: true
+  #       id: test
+  #       with:
+  #         github_token: ${{ secrets.github_token }}
+  #         reporter: github-pr-review
+  #         level: info
+  #         working_directory: testdata
 
-      # The check is expected to fail on the test data
-      #  but for forked PRs reviewdog will just output
-      #  on the PR and report success
-      - name: Check return codes
-        if: success() || failure ()
-        run: |
-          tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
-          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
-          if [[ "$tfsec_return" -eq 1 ]]; then
-            echo "tfsec correctly returned failure ${tfsec_return}"
-          else
-            echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
-            exit 1
-          fi
-          if [[ "$reviewdog_return" -eq 0 ]]; then
-            echo "reviewdog correctly returned success: ${reviewdog_return}"
-          else
-            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
-            exit 1
-          fi
+  #     # The check is expected to fail on the test data
+  #     #  but for forked PRs reviewdog will just output
+  #     #  on the PR and report success
+  #     - name: Check return codes
+  #       if: success() || failure ()
+  #       run: |
+  #         tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
+  #         reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
+  #         if [[ "$tfsec_return" -eq 1 ]]; then
+  #           echo "tfsec correctly returned failure ${tfsec_return}"
+  #         else
+  #           echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
+  #           exit 1
+  #         fi
+  #         if [[ "$reviewdog_return" -eq 0 ]]; then
+  #           echo "reviewdog correctly returned success: ${reviewdog_return}"
+  #         else
+  #           echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
+  #           exit 1
+  #         fi
