change pipeline

diff --git a/.github/workflows/tfsec.yaml b/.github/workflows/tfsec.yaml
--- a/.github/workflows/tfsec.yaml
+++ b/.github/workflows/tfsec.yaml
@@ -14,31 +14,19 @@ jobs:
         - name: Clone repo
           uses: actions/checkout@master
         - name: tfsec
+          id  : test
           uses: aquasecurity/tfsec-action@v1.0.0
           with:
             soft_fail: true
+        - name: Check return codes
+          if: success() || failure ()
+          run: |
+            tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
+            reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
+            if [[ "$tfsec_return" -eq 1 ]]; then
+              echo "tfsec correctly returned failure ${tfsec_return}"
+            else
+              echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
+              exit 1
+            fi
 
-  tfsec-pr-check:
-    name: tfsec (github-pr-check)
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v3
-      # The check is expected to fail on the test data
-      - name: Check return codes
-        if: success() || failure ()
-        run: |
-          tfsec_return="${{ steps.test.outputs.tfsec-return-code }}"
-          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"
-          if [[ "$tfsec_return" -eq 1 ]]; then
-            echo "tfsec correctly returned failure ${tfsec_return}"
-          else
-            echo "tfsec returned ${tfsec_return}, expected '1'. Failing..."
-            exit 1
-          fi
-          if [[ "$reviewdog_return" -eq 0 ]]; then
-            echo "reviewdog correctly returned success: ${reviewdog_return}"
-          else
-            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
-            exit 1
-          fi
